### ISSUE TITLE
Error when using the reload callback

### ISSUE THREAD

**Issue by Leonardo-DGS** [Simplix-Softworks/SimplixStorage#56]
**Describe the bug**
When the reload callback is executed, there is throw an error.

**To Reproduce**
1. With the LightningBuilder set a reload callback and use the FlatFile argument.
2. When the reload callback is executed, is thrown an Exception

**Screenshots**
![LightningValidationException](https://user-images.githubusercontent.com/17832817/137661015-b54637c8-8032-4def-bf81-54e191725c23.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
**Java**
 - Version: 17

**Additional context**
`[Server thread/ERROR]: Error occurred while enabling InteractiveBooks v1.5.6 (Is it up to date?)
net.leonardo_dgs.interactivebooks.simplixstorage.internal.exceptions.LightningValidationException: FileData mustn't be null
        at net.leonardo_dgs.interactivebooks.simplixstorage.util.Valid.notNull(Valid.java:36) ~[?:?]
        at net.leonardo_dgs.interactivebooks.simplixstorage.internal.FlatFile.getFileData(FlatFile.java:341) ~[?:?]
        at net.leonardo_dgs.interactivebooks.simplixstorage.internal.FlatFile.get(FlatFile.java:142) ~[?:?]
        at net.leonardo_dgs.interactivebooks.simplixstorage.internal.DataStorage.getOrDefault(DataStorage.java:285) ~[?:?]
        at net.leonardo_dgs.interactivebooks.simplixstorage.internal.DataStorage.getString(DataStorage.java:113) ~[?:?]
        at net.leonardo_dgs.interactivebooks.ConfigManager.registerBook(ConfigManager.java:64) ~[?:?]
        at net.leonardo_dgs.interactivebooks.ConfigManager.lambda$loadBookConfigs$0(ConfigManager.java:55) ~[?:?]
        at net.leonardo_dgs.interactivebooks.simplixstorage.internal.FlatFile.forceReload(FlatFile.java:291) ~[?:?]
        at net.leonardo_dgs.interactivebooks.simplixstorage.Yaml.<init>(Yaml.java:101) ~[?:?]
        at net.leonardo_dgs.interactivebooks.simplixstorage.Config.<init>(Config.java:53) ~[?:?]
        at net.leonardo_dgs.interactivebooks.simplixstorage.LightningBuilder.createConfig(LightningBuilder.java:128) ~[?:?]
        at net.leonardo_dgs.interactivebooks.ConfigManager.loadBookConfigs(ConfigManager.java:57) ~[?:?]
        at net.leonardo_dgs.interactivebooks.ConfigManager.loadAll(ConfigManager.java:30) ~[?:?]
        at net.leonardo_dgs.interactivebooks.InteractiveBooks.onEnable(InteractiveBooks.java:35) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:514) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:428) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:619) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3242-Spigot-6c1c1b2-d3cc412]
        at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by KotlinFactory** [comment]
Hey,
is this fixed with the latest version?

Regards,
Leonhard

**Comment by KotlinFactory** [comment]
Should be resolved with the latest version.
